services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend/app.py:/app/app.py
      - ./backend/saved_model:/app/saved_model
    environment:
      - FLASK_DEBUG=1
    container_name: credit-card-backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: credit-card-frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
